services:
  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    restart: always
    env_file:
      - .env.prod
    volumes:
      - storage_app:/var/www/html/storage/app
      - storage_framework:/var/www/html/storage/framework
      - storage_logs:/var/www/html/storage/logs
      - public_data:/var/www/html/public_shared
    networks:
      - app-network

  web:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/production/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - public_data:/var/www/html/public
      - storage_app:/var/www/html/storage/app
    depends_on:
      - app
    networks:
      - app-network

  database:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # migration:
  #   build:
  #     context: .
  #     dockerfile: docker/production/Dockerfile
  #   command: php artisan migrate --force
  #   env_file:
  #     - .env.prod
  #   depends_on:
  #     - database
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  storage_app:
  storage_framework:
  storage_logs:
  public_data:
